FROM python:3.10-slim

WORKDIR /app
COPY backend/ /app/

RUN apt-get update && apt-get install -y ffmpeg libmagic1 && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--proxy-headers", "--log-level", "info"]